version: "3.9"

services:
  db:
    image: postgres
    container_name: wmc-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network-wmc-app

  rails:
    build: .
    container_name: wmc-rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/web-medical-clinic
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - network-wmc-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

networks: 
  network-wmc-app:
    driver: bridge

volumes:
    postgres_database:
        external: true
