version: "3.9"

services:
  db:
    image: postgres
    container_name: wmc-postgres-container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data" 
    networks:
      - wmc-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: wmc-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    depends_on:
      - db
    networks:
      - wmc-network

  rails:
    build: .
    container_name: "wmc-rails-container"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/web-medical-clinic
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - wmc-network

networks: 
  wmc-network:
    driver: bridge